# This template will generate a list of jobs that will run. The
# jobs created will correspond to the cross product of the
# vmImages and goVersions specified by the parameters.

parameters:
  goVersions: []
  vmImages: []

jobs:

- job: build
  displayName: 'Build: '

  # Build on each combination of supported OS and Go version
  strategy:
    matrix:
      ${{ each goVersion in parameters.goVersions }}:
        ${{ each vmImage in parameters.vmImages }}:
          OS_${{ vmImage.ymlSafeName }}_GO_${{ goVersion.ymlSafeName }}:
            vmImage: ${{ vmImage.value }}
            goVersion: ${{ goVersion.value }}
  
  pool:
    vmImage: $(vmImage)

  steps:
  - task: GoTool@0
    displayName: 'Install correct version of Go'
    inputs:
      version: $(goVersion)

  - bash: |
      #!/usr/bin/env bash
      cd "$BUILD_SOURCESDIRECTORY"
      chmod +x ./scripts/*.sh
    displayName: 'Set Scripts as Executable'

  - bash: |
      #!/usr/bin/env bash
      cd "$BUILD_SOURCESDIRECTORY"
      ./scripts/fmt-check-go.sh
    displayName: 'Run Format Check'

  - bash: |
      #!/usr/bin/env bash
      cd "$BUILD_SOURCESDIRECTORY"
      go get -u golang.org/x/lint/golint
      ./scripts/lint-check-go.sh
    displayName: 'Run Lint Check'

  - bash: |
      #!/usr/bin/env bash
      cd "$BUILD_SOURCESDIRECTORY"
      ./scripts/build.sh
    displayName: 'Run Build Script'

  - bash: |
      #!/usr/bin/env bash
      cd "$BUILD_SOURCESDIRECTORY"
      ./scripts/acctest.sh
    displayName: 'Run Acceptance Tests'
    env:
      AZDO_ORG_SERVICE_URL: $(ACC_TEST_AZDO_ORG_URL)
      AZDO_PERSONAL_ACCESS_TOKEN: $(ACC_TEST_AZDO_PAT)
      AZDO_GITHUB_SERVICE_CONNECTION_PAT: $(ACC_TEST_GH_PAT)
      AZDO_DOCKERHUB_SERVICE_CONNECTION_USERNAME: $(AZDO_DOCKERHUB_SERVICE_CONNECTION_USERNAME)
      AZDO_DOCKERHUB_SERVICE_CONNECTION_EMAIL: $(AZDO_DOCKERHUB_SERVICE_CONNECTION_EMAIL)
      AZDO_DOCKERHUB_SERVICE_CONNECTION_PASSWORD: $(AZDO_DOCKERHUB_SERVICE_CONNECTION_PASSWORD)

  - bash: docker build -t dev --build-arg GO_VERSION=${GO_VERSION} .
    env:
      GO_VERSION: $(goVersion)
    displayName: 'Run Build Script in Docker'

  - bash: |
      docker run --env AZDO_ORG_SERVICE_URL=${AZDO_ORG_SERVICE_URL} \
      --env AZDO_PERSONAL_ACCESS_TOKEN=${AZDO_PERSONAL_ACCESS_TOKEN} \
      --env AZDO_GITHUB_SERVICE_CONNECTION_PAT=${AZDO_GITHUB_SERVICE_CONNECTION_PAT} \
      --env AZDO_TEST_AAD_USER_EMAIL=${AZDO_TEST_AAD_USER_EMAIL} \
      --env AZDO_DOCKERHUB_SERVICE_CONNECTION_USERNAME=${AZDO_DOCKERHUB_SERVICE_CONNECTION_USERNAME} \
      --env AZDO_DOCKERHUB_SERVICE_CONNECTION_EMAIL=${AZDO_DOCKERHUB_SERVICE_CONNECTION_EMAIL} \
      --env AZDO_DOCKERHUB_SERVICE_CONNECTION_PASSWORD=${AZDO_DOCKERHUB_SERVICE_CONNECTION_PASSWORD} \
      -v ${PWD}:/root/workspace dev ./scripts/acctest.sh
    env:
      AZDO_ORG_SERVICE_URL: $(ACC_TEST_AZDO_ORG_URL)
      AZDO_PERSONAL_ACCESS_TOKEN: $(ACC_TEST_AZDO_PAT)
      AZDO_GITHUB_SERVICE_CONNECTION_PAT: $(ACC_TEST_GH_PAT)
      AZDO_DOCKERHUB_SERVICE_CONNECTION_USERNAME: $(AZDO_DOCKERHUB_SERVICE_CONNECTION_USERNAME)
      AZDO_DOCKERHUB_SERVICE_CONNECTION_EMAIL: $(AZDO_DOCKERHUB_SERVICE_CONNECTION_EMAIL)
      AZDO_DOCKERHUB_SERVICE_CONNECTION_PASSWORD: $(AZDO_DOCKERHUB_SERVICE_CONNECTION_PASSWORD)
    displayName: 'Run Acceptance Tests in Docker'
